#:schema node_modules/wrangler/config-schema.json
name = "quickr"
compatibility_date = "2024-10-04"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "quickr"
database_id = "5dd2d7c2-adf8-4b2f-8a92-bc2389db5bb6"
migrations_dir = "../image-optimizer/migrations"
