#:schema node_modules/wrangler/config-schema.json
name = "quickr"
compatibility_date = "2024-10-04"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "quickr"
database_id = "8f92c3b1-e510-4617-b804-449494bc432d"
preview_database_id = "quickr_dev"
migrations_dir = "../image-optimizer/migrations"
