#:schema node_modules/wrangler/config-schema.json
name = "image-optimizer"
main = "src/index.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
route = { pattern = "*-cdn.quickr.dev/*", zone_name = "quickr.dev" }

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "quickr"
database_id = "8f92c3b1-e510-4617-b804-449494bc432d"
preview_database_id = "quickr_dev"
