#:schema node_modules/wrangler/config-schema.json
name = "image-optimizer"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
route = { pattern = "*.quickr.dev", zone_name = "quickr.dev" }

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "quickr"
database_id = "40d7f4ec-ebb9-40dc-9251-5801307196a5"
